all:
	g++ -O0 -Wall -o hw1p2_O0 hw1p2.cpp
	g++ -O1 -Wall -o hw1p2_O1 hw1p2.cpp
	g++ -O2 -Wall -o hw1p2_O2 hw1p2.cpp
	g++ -O3 -Wall -o hw1p2_O3 hw1p2.cpp
	g++ -Ofast -Wall -o hw1p2_Ofast hw1p2.cpp
	g++ -Og -Wall -o hw1p2_Og hw1p2.cpp
	g++ -Os -Wall -o hw1p2_Os hw1p2.cpp

clean:
	rm -f hw1p2_O0 hw1p2_O1 hw1p2_O2 hw1p2_O3 hw1p2_Ofast hw1p2_Og hw1p2_Os